//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.06 at 02:30:42 午後 JST 
//


package org.dbgrid.csw.schema.search;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.dbgrid.csw.schema.search package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.dbgrid.csw.schema.search
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SearchConfig }
     * 
     */
    public SearchConfig createSearchConfig() {
        return new SearchConfig();
    }

    /**
     * Create an instance of {@link SearchConfig.LuceneField }
     * 
     */
    public SearchConfig.LuceneField createSearchConfigLuceneField() {
        return new SearchConfig.LuceneField();
    }

    /**
     * Create an instance of {@link SearchConfig.LuceneField.Property }
     * 
     */
    public SearchConfig.LuceneField.Property createSearchConfigLuceneFieldProperty() {
        return new SearchConfig.LuceneField.Property();
    }

}
