//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.31 at 04:35:10 午後 JST 
//


package org.dbgrid.csw.schema.crawler;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="LuceneField">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="property" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="xpath">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;choice>
 *                                         &lt;element name="statement" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *                                         &lt;element name="bbox">
 *                                           &lt;complexType>
 *                                             &lt;complexContent>
 *                                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                 &lt;sequence>
 *                                                   &lt;choice>
 *                                                     &lt;element name="Envelope">
 *                                                       &lt;complexType>
 *                                                         &lt;complexContent>
 *                                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                             &lt;sequence>
 *                                                               &lt;element name="srsName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                               &lt;element name="lower" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                               &lt;element name="upper" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                             &lt;/sequence>
 *                                                           &lt;/restriction>
 *                                                         &lt;/complexContent>
 *                                                       &lt;/complexType>
 *                                                     &lt;/element>
 *                                                     &lt;element name="NWES">
 *                                                       &lt;complexType>
 *                                                         &lt;complexContent>
 *                                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                             &lt;sequence>
 *                                                               &lt;element name="srsName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                               &lt;element name="north" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                               &lt;element name="south" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                               &lt;element name="west" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                               &lt;element name="east" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                             &lt;/sequence>
 *                                                           &lt;/restriction>
 *                                                         &lt;/complexContent>
 *                                                       &lt;/complexType>
 *                                                     &lt;/element>
 *                                                   &lt;/choice>
 *                                                   &lt;element name="bboxType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;/sequence>
 *                                               &lt;/restriction>
 *                                             &lt;/complexContent>
 *                                           &lt;/complexType>
 *                                         &lt;/element>
 *                                         &lt;element name="polygon">
 *                                           &lt;complexType>
 *                                             &lt;complexContent>
 *                                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                 &lt;sequence>
 *                                                   &lt;element name="exterior" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                   &lt;element name="interior" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                                                 &lt;/sequence>
 *                                               &lt;/restriction>
 *                                             &lt;/complexContent>
 *                                           &lt;/complexType>
 *                                         &lt;/element>
 *                                         &lt;element name="point">
 *                                           &lt;complexType>
 *                                             &lt;complexContent>
 *                                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                 &lt;sequence>
 *                                                   &lt;element name="pointType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                   &lt;choice>
 *                                                     &lt;element name="latlon">
 *                                                       &lt;complexType>
 *                                                         &lt;complexContent>
 *                                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                             &lt;sequence>
 *                                                               &lt;element name="lat" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                               &lt;element name="long" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                             &lt;/sequence>
 *                                                           &lt;/restriction>
 *                                                         &lt;/complexContent>
 *                                                       &lt;/complexType>
 *                                                     &lt;/element>
 *                                                   &lt;/choice>
 *                                                 &lt;/sequence>
 *                                               &lt;/restriction>
 *                                             &lt;/complexContent>
 *                                           &lt;/complexType>
 *                                         &lt;/element>
 *                                       &lt;/choice>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="datatype" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="field" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="multi" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                             &lt;element name="analyzer" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="summary" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="brief" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="json" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="NamespaceList">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="namespace" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="DateFormat" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="projection" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "luceneField",
    "namespaceList",
    "dateFormat",
    "projection"
})
@XmlRootElement(name = "CrawlerConfig")
public class CrawlerConfig {

    @XmlElement(name = "LuceneField", required = true)
    protected CrawlerConfig.LuceneField luceneField;
    @XmlElement(name = "NamespaceList", required = true)
    protected CrawlerConfig.NamespaceList namespaceList;
    @XmlElement(name = "DateFormat", required = true)
    protected String dateFormat;
    @XmlElement(required = true)
    protected String projection;

    /**
     * Gets the value of the luceneField property.
     * 
     * @return
     *     possible object is
     *     {@link CrawlerConfig.LuceneField }
     *     
     */
    public CrawlerConfig.LuceneField getLuceneField() {
        return luceneField;
    }

    /**
     * Sets the value of the luceneField property.
     * 
     * @param value
     *     allowed object is
     *     {@link CrawlerConfig.LuceneField }
     *     
     */
    public void setLuceneField(CrawlerConfig.LuceneField value) {
        this.luceneField = value;
    }

    /**
     * Gets the value of the namespaceList property.
     * 
     * @return
     *     possible object is
     *     {@link CrawlerConfig.NamespaceList }
     *     
     */
    public CrawlerConfig.NamespaceList getNamespaceList() {
        return namespaceList;
    }

    /**
     * Sets the value of the namespaceList property.
     * 
     * @param value
     *     allowed object is
     *     {@link CrawlerConfig.NamespaceList }
     *     
     */
    public void setNamespaceList(CrawlerConfig.NamespaceList value) {
        this.namespaceList = value;
    }

    /**
     * Gets the value of the dateFormat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateFormat() {
        return dateFormat;
    }

    /**
     * Sets the value of the dateFormat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateFormat(String value) {
        this.dateFormat = value;
    }

    /**
     * Gets the value of the projection property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProjection() {
        return projection;
    }

    /**
     * Sets the value of the projection property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProjection(String value) {
        this.projection = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="property" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="xpath">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;choice>
     *                               &lt;element name="statement" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
     *                               &lt;element name="bbox">
     *                                 &lt;complexType>
     *                                   &lt;complexContent>
     *                                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                       &lt;sequence>
     *                                         &lt;choice>
     *                                           &lt;element name="Envelope">
     *                                             &lt;complexType>
     *                                               &lt;complexContent>
     *                                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                                   &lt;sequence>
     *                                                     &lt;element name="srsName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                                     &lt;element name="lower" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                                     &lt;element name="upper" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                                   &lt;/sequence>
     *                                                 &lt;/restriction>
     *                                               &lt;/complexContent>
     *                                             &lt;/complexType>
     *                                           &lt;/element>
     *                                           &lt;element name="NWES">
     *                                             &lt;complexType>
     *                                               &lt;complexContent>
     *                                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                                   &lt;sequence>
     *                                                     &lt;element name="srsName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                                     &lt;element name="north" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                                     &lt;element name="south" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                                     &lt;element name="west" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                                     &lt;element name="east" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                                   &lt;/sequence>
     *                                                 &lt;/restriction>
     *                                               &lt;/complexContent>
     *                                             &lt;/complexType>
     *                                           &lt;/element>
     *                                         &lt;/choice>
     *                                         &lt;element name="bboxType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;/sequence>
     *                                     &lt;/restriction>
     *                                   &lt;/complexContent>
     *                                 &lt;/complexType>
     *                               &lt;/element>
     *                               &lt;element name="polygon">
     *                                 &lt;complexType>
     *                                   &lt;complexContent>
     *                                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                       &lt;sequence>
     *                                         &lt;element name="exterior" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                         &lt;element name="interior" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *                                       &lt;/sequence>
     *                                     &lt;/restriction>
     *                                   &lt;/complexContent>
     *                                 &lt;/complexType>
     *                               &lt;/element>
     *                               &lt;element name="point">
     *                                 &lt;complexType>
     *                                   &lt;complexContent>
     *                                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                       &lt;sequence>
     *                                         &lt;element name="pointType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                         &lt;choice>
     *                                           &lt;element name="latlon">
     *                                             &lt;complexType>
     *                                               &lt;complexContent>
     *                                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                                   &lt;sequence>
     *                                                     &lt;element name="lat" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                                     &lt;element name="long" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                                   &lt;/sequence>
     *                                                 &lt;/restriction>
     *                                               &lt;/complexContent>
     *                                             &lt;/complexType>
     *                                           &lt;/element>
     *                                         &lt;/choice>
     *                                       &lt;/sequence>
     *                                     &lt;/restriction>
     *                                   &lt;/complexContent>
     *                                 &lt;/complexType>
     *                               &lt;/element>
     *                             &lt;/choice>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="datatype" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="field" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="multi" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                   &lt;element name="analyzer" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="summary" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="brief" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="json" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "property"
    })
    public static class LuceneField {

        @XmlElement(required = true)
        protected List<CrawlerConfig.LuceneField.Property> property;

        /**
         * Gets the value of the property property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the property property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getProperty().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link CrawlerConfig.LuceneField.Property }
         * 
         * 
         */
        public List<CrawlerConfig.LuceneField.Property> getProperty() {
            if (property == null) {
                property = new ArrayList<CrawlerConfig.LuceneField.Property>();
            }
            return this.property;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="xpath">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;choice>
         *                     &lt;element name="statement" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
         *                     &lt;element name="bbox">
         *                       &lt;complexType>
         *                         &lt;complexContent>
         *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                             &lt;sequence>
         *                               &lt;choice>
         *                                 &lt;element name="Envelope">
         *                                   &lt;complexType>
         *                                     &lt;complexContent>
         *                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                                         &lt;sequence>
         *                                           &lt;element name="srsName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                                           &lt;element name="lower" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                                           &lt;element name="upper" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                                         &lt;/sequence>
         *                                       &lt;/restriction>
         *                                     &lt;/complexContent>
         *                                   &lt;/complexType>
         *                                 &lt;/element>
         *                                 &lt;element name="NWES">
         *                                   &lt;complexType>
         *                                     &lt;complexContent>
         *                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                                         &lt;sequence>
         *                                           &lt;element name="srsName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                                           &lt;element name="north" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                                           &lt;element name="south" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                                           &lt;element name="west" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                                           &lt;element name="east" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                                         &lt;/sequence>
         *                                       &lt;/restriction>
         *                                     &lt;/complexContent>
         *                                   &lt;/complexType>
         *                                 &lt;/element>
         *                               &lt;/choice>
         *                               &lt;element name="bboxType" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;/sequence>
         *                           &lt;/restriction>
         *                         &lt;/complexContent>
         *                       &lt;/complexType>
         *                     &lt;/element>
         *                     &lt;element name="polygon">
         *                       &lt;complexType>
         *                         &lt;complexContent>
         *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                             &lt;sequence>
         *                               &lt;element name="exterior" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                               &lt;element name="interior" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
         *                             &lt;/sequence>
         *                           &lt;/restriction>
         *                         &lt;/complexContent>
         *                       &lt;/complexType>
         *                     &lt;/element>
         *                     &lt;element name="point">
         *                       &lt;complexType>
         *                         &lt;complexContent>
         *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                             &lt;sequence>
         *                               &lt;element name="pointType" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                               &lt;choice>
         *                                 &lt;element name="latlon">
         *                                   &lt;complexType>
         *                                     &lt;complexContent>
         *                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                                         &lt;sequence>
         *                                           &lt;element name="lat" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                                           &lt;element name="long" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                                         &lt;/sequence>
         *                                       &lt;/restriction>
         *                                     &lt;/complexContent>
         *                                   &lt;/complexType>
         *                                 &lt;/element>
         *                               &lt;/choice>
         *                             &lt;/sequence>
         *                           &lt;/restriction>
         *                         &lt;/complexContent>
         *                       &lt;/complexType>
         *                     &lt;/element>
         *                   &lt;/choice>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="datatype" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="field" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="multi" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *         &lt;element name="analyzer" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="summary" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="brief" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="json" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "xpath",
            "datatype",
            "field",
            "multi",
            "analyzer",
            "summary",
            "brief",
            "json"
        })
        public static class Property {

            @XmlElement(required = true)
            protected CrawlerConfig.LuceneField.Property.Xpath xpath;
            @XmlElement(required = true)
            protected String datatype;
            @XmlElement(required = true)
            protected String field;
            protected boolean multi;
            @XmlElement(required = true)
            protected String analyzer;
            protected String summary;
            protected String brief;
            protected String json;

            /**
             * Gets the value of the xpath property.
             * 
             * @return
             *     possible object is
             *     {@link CrawlerConfig.LuceneField.Property.Xpath }
             *     
             */
            public CrawlerConfig.LuceneField.Property.Xpath getXpath() {
                return xpath;
            }

            /**
             * Sets the value of the xpath property.
             * 
             * @param value
             *     allowed object is
             *     {@link CrawlerConfig.LuceneField.Property.Xpath }
             *     
             */
            public void setXpath(CrawlerConfig.LuceneField.Property.Xpath value) {
                this.xpath = value;
            }

            /**
             * Gets the value of the datatype property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDatatype() {
                return datatype;
            }

            /**
             * Sets the value of the datatype property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDatatype(String value) {
                this.datatype = value;
            }

            /**
             * Gets the value of the field property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getField() {
                return field;
            }

            /**
             * Sets the value of the field property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setField(String value) {
                this.field = value;
            }

            /**
             * Gets the value of the multi property.
             * 
             */
            public boolean isMulti() {
                return multi;
            }

            /**
             * Sets the value of the multi property.
             * 
             */
            public void setMulti(boolean value) {
                this.multi = value;
            }

            /**
             * Gets the value of the analyzer property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAnalyzer() {
                return analyzer;
            }

            /**
             * Sets the value of the analyzer property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAnalyzer(String value) {
                this.analyzer = value;
            }

            /**
             * Gets the value of the summary property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSummary() {
                return summary;
            }

            /**
             * Sets the value of the summary property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSummary(String value) {
                this.summary = value;
            }

            /**
             * Gets the value of the brief property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBrief() {
                return brief;
            }

            /**
             * Sets the value of the brief property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBrief(String value) {
                this.brief = value;
            }

            /**
             * Gets the value of the json property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getJson() {
                return json;
            }

            /**
             * Sets the value of the json property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setJson(String value) {
                this.json = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;choice>
             *           &lt;element name="statement" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
             *           &lt;element name="bbox">
             *             &lt;complexType>
             *               &lt;complexContent>
             *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                   &lt;sequence>
             *                     &lt;choice>
             *                       &lt;element name="Envelope">
             *                         &lt;complexType>
             *                           &lt;complexContent>
             *                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                               &lt;sequence>
             *                                 &lt;element name="srsName" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                                 &lt;element name="lower" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                                 &lt;element name="upper" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                               &lt;/sequence>
             *                             &lt;/restriction>
             *                           &lt;/complexContent>
             *                         &lt;/complexType>
             *                       &lt;/element>
             *                       &lt;element name="NWES">
             *                         &lt;complexType>
             *                           &lt;complexContent>
             *                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                               &lt;sequence>
             *                                 &lt;element name="srsName" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                                 &lt;element name="north" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                                 &lt;element name="south" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                                 &lt;element name="west" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                                 &lt;element name="east" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                               &lt;/sequence>
             *                             &lt;/restriction>
             *                           &lt;/complexContent>
             *                         &lt;/complexType>
             *                       &lt;/element>
             *                     &lt;/choice>
             *                     &lt;element name="bboxType" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;/sequence>
             *                 &lt;/restriction>
             *               &lt;/complexContent>
             *             &lt;/complexType>
             *           &lt;/element>
             *           &lt;element name="polygon">
             *             &lt;complexType>
             *               &lt;complexContent>
             *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                   &lt;sequence>
             *                     &lt;element name="exterior" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                     &lt;element name="interior" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
             *                   &lt;/sequence>
             *                 &lt;/restriction>
             *               &lt;/complexContent>
             *             &lt;/complexType>
             *           &lt;/element>
             *           &lt;element name="point">
             *             &lt;complexType>
             *               &lt;complexContent>
             *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                   &lt;sequence>
             *                     &lt;element name="pointType" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                     &lt;choice>
             *                       &lt;element name="latlon">
             *                         &lt;complexType>
             *                           &lt;complexContent>
             *                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                               &lt;sequence>
             *                                 &lt;element name="lat" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                                 &lt;element name="long" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                               &lt;/sequence>
             *                             &lt;/restriction>
             *                           &lt;/complexContent>
             *                         &lt;/complexType>
             *                       &lt;/element>
             *                     &lt;/choice>
             *                   &lt;/sequence>
             *                 &lt;/restriction>
             *               &lt;/complexContent>
             *             &lt;/complexType>
             *           &lt;/element>
             *         &lt;/choice>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "statement",
                "bbox",
                "polygon",
                "point"
            })
            public static class Xpath {

                protected List<String> statement;
                protected CrawlerConfig.LuceneField.Property.Xpath.Bbox bbox;
                protected CrawlerConfig.LuceneField.Property.Xpath.Polygon polygon;
                protected CrawlerConfig.LuceneField.Property.Xpath.Point point;

                /**
                 * Gets the value of the statement property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the statement property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getStatement().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link String }
                 * 
                 * 
                 */
                public List<String> getStatement() {
                    if (statement == null) {
                        statement = new ArrayList<String>();
                    }
                    return this.statement;
                }

                /**
                 * Gets the value of the bbox property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link CrawlerConfig.LuceneField.Property.Xpath.Bbox }
                 *     
                 */
                public CrawlerConfig.LuceneField.Property.Xpath.Bbox getBbox() {
                    return bbox;
                }

                /**
                 * Sets the value of the bbox property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link CrawlerConfig.LuceneField.Property.Xpath.Bbox }
                 *     
                 */
                public void setBbox(CrawlerConfig.LuceneField.Property.Xpath.Bbox value) {
                    this.bbox = value;
                }

                /**
                 * Gets the value of the polygon property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link CrawlerConfig.LuceneField.Property.Xpath.Polygon }
                 *     
                 */
                public CrawlerConfig.LuceneField.Property.Xpath.Polygon getPolygon() {
                    return polygon;
                }

                /**
                 * Sets the value of the polygon property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link CrawlerConfig.LuceneField.Property.Xpath.Polygon }
                 *     
                 */
                public void setPolygon(CrawlerConfig.LuceneField.Property.Xpath.Polygon value) {
                    this.polygon = value;
                }

                /**
                 * Gets the value of the point property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link CrawlerConfig.LuceneField.Property.Xpath.Point }
                 *     
                 */
                public CrawlerConfig.LuceneField.Property.Xpath.Point getPoint() {
                    return point;
                }

                /**
                 * Sets the value of the point property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link CrawlerConfig.LuceneField.Property.Xpath.Point }
                 *     
                 */
                public void setPoint(CrawlerConfig.LuceneField.Property.Xpath.Point value) {
                    this.point = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;choice>
                 *           &lt;element name="Envelope">
                 *             &lt;complexType>
                 *               &lt;complexContent>
                 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *                   &lt;sequence>
                 *                     &lt;element name="srsName" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *                     &lt;element name="lower" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *                     &lt;element name="upper" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *                   &lt;/sequence>
                 *                 &lt;/restriction>
                 *               &lt;/complexContent>
                 *             &lt;/complexType>
                 *           &lt;/element>
                 *           &lt;element name="NWES">
                 *             &lt;complexType>
                 *               &lt;complexContent>
                 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *                   &lt;sequence>
                 *                     &lt;element name="srsName" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *                     &lt;element name="north" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *                     &lt;element name="south" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *                     &lt;element name="west" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *                     &lt;element name="east" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *                   &lt;/sequence>
                 *                 &lt;/restriction>
                 *               &lt;/complexContent>
                 *             &lt;/complexType>
                 *           &lt;/element>
                 *         &lt;/choice>
                 *         &lt;element name="bboxType" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "envelope",
                    "nwes",
                    "bboxType"
                })
                public static class Bbox {

                    @XmlElement(name = "Envelope")
                    protected CrawlerConfig.LuceneField.Property.Xpath.Bbox.Envelope envelope;
                    @XmlElement(name = "NWES")
                    protected CrawlerConfig.LuceneField.Property.Xpath.Bbox.NWES nwes;
                    @XmlElement(required = true)
                    protected String bboxType;

                    /**
                     * Gets the value of the envelope property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link CrawlerConfig.LuceneField.Property.Xpath.Bbox.Envelope }
                     *     
                     */
                    public CrawlerConfig.LuceneField.Property.Xpath.Bbox.Envelope getEnvelope() {
                        return envelope;
                    }

                    /**
                     * Sets the value of the envelope property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link CrawlerConfig.LuceneField.Property.Xpath.Bbox.Envelope }
                     *     
                     */
                    public void setEnvelope(CrawlerConfig.LuceneField.Property.Xpath.Bbox.Envelope value) {
                        this.envelope = value;
                    }

                    /**
                     * Gets the value of the nwes property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link CrawlerConfig.LuceneField.Property.Xpath.Bbox.NWES }
                     *     
                     */
                    public CrawlerConfig.LuceneField.Property.Xpath.Bbox.NWES getNWES() {
                        return nwes;
                    }

                    /**
                     * Sets the value of the nwes property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link CrawlerConfig.LuceneField.Property.Xpath.Bbox.NWES }
                     *     
                     */
                    public void setNWES(CrawlerConfig.LuceneField.Property.Xpath.Bbox.NWES value) {
                        this.nwes = value;
                    }

                    /**
                     * Gets the value of the bboxType property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getBboxType() {
                        return bboxType;
                    }

                    /**
                     * Sets the value of the bboxType property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setBboxType(String value) {
                        this.bboxType = value;
                    }


                    /**
                     * <p>Java class for anonymous complex type.
                     * 
                     * <p>The following schema fragment specifies the expected content contained within this class.
                     * 
                     * <pre>
                     * &lt;complexType>
                     *   &lt;complexContent>
                     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                     *       &lt;sequence>
                     *         &lt;element name="srsName" type="{http://www.w3.org/2001/XMLSchema}string"/>
                     *         &lt;element name="lower" type="{http://www.w3.org/2001/XMLSchema}string"/>
                     *         &lt;element name="upper" type="{http://www.w3.org/2001/XMLSchema}string"/>
                     *       &lt;/sequence>
                     *     &lt;/restriction>
                     *   &lt;/complexContent>
                     * &lt;/complexType>
                     * </pre>
                     * 
                     * 
                     */
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = {
                        "srsName",
                        "lower",
                        "upper"
                    })
                    public static class Envelope {

                        @XmlElement(required = true)
                        protected String srsName;
                        @XmlElement(required = true)
                        protected String lower;
                        @XmlElement(required = true)
                        protected String upper;

                        /**
                         * Gets the value of the srsName property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getSrsName() {
                            return srsName;
                        }

                        /**
                         * Sets the value of the srsName property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setSrsName(String value) {
                            this.srsName = value;
                        }

                        /**
                         * Gets the value of the lower property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getLower() {
                            return lower;
                        }

                        /**
                         * Sets the value of the lower property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setLower(String value) {
                            this.lower = value;
                        }

                        /**
                         * Gets the value of the upper property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getUpper() {
                            return upper;
                        }

                        /**
                         * Sets the value of the upper property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setUpper(String value) {
                            this.upper = value;
                        }

                    }


                    /**
                     * <p>Java class for anonymous complex type.
                     * 
                     * <p>The following schema fragment specifies the expected content contained within this class.
                     * 
                     * <pre>
                     * &lt;complexType>
                     *   &lt;complexContent>
                     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                     *       &lt;sequence>
                     *         &lt;element name="srsName" type="{http://www.w3.org/2001/XMLSchema}string"/>
                     *         &lt;element name="north" type="{http://www.w3.org/2001/XMLSchema}string"/>
                     *         &lt;element name="south" type="{http://www.w3.org/2001/XMLSchema}string"/>
                     *         &lt;element name="west" type="{http://www.w3.org/2001/XMLSchema}string"/>
                     *         &lt;element name="east" type="{http://www.w3.org/2001/XMLSchema}string"/>
                     *       &lt;/sequence>
                     *     &lt;/restriction>
                     *   &lt;/complexContent>
                     * &lt;/complexType>
                     * </pre>
                     * 
                     * 
                     */
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = {
                        "srsName",
                        "north",
                        "south",
                        "west",
                        "east"
                    })
                    public static class NWES {

                        @XmlElement(required = true)
                        protected String srsName;
                        @XmlElement(required = true)
                        protected String north;
                        @XmlElement(required = true)
                        protected String south;
                        @XmlElement(required = true)
                        protected String west;
                        @XmlElement(required = true)
                        protected String east;

                        /**
                         * Gets the value of the srsName property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getSrsName() {
                            return srsName;
                        }

                        /**
                         * Sets the value of the srsName property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setSrsName(String value) {
                            this.srsName = value;
                        }

                        /**
                         * Gets the value of the north property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getNorth() {
                            return north;
                        }

                        /**
                         * Sets the value of the north property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setNorth(String value) {
                            this.north = value;
                        }

                        /**
                         * Gets the value of the south property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getSouth() {
                            return south;
                        }

                        /**
                         * Sets the value of the south property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setSouth(String value) {
                            this.south = value;
                        }

                        /**
                         * Gets the value of the west property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getWest() {
                            return west;
                        }

                        /**
                         * Sets the value of the west property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setWest(String value) {
                            this.west = value;
                        }

                        /**
                         * Gets the value of the east property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getEast() {
                            return east;
                        }

                        /**
                         * Sets the value of the east property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setEast(String value) {
                            this.east = value;
                        }

                    }

                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="pointType" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;choice>
                 *           &lt;element name="latlon">
                 *             &lt;complexType>
                 *               &lt;complexContent>
                 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *                   &lt;sequence>
                 *                     &lt;element name="lat" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *                     &lt;element name="long" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *                   &lt;/sequence>
                 *                 &lt;/restriction>
                 *               &lt;/complexContent>
                 *             &lt;/complexType>
                 *           &lt;/element>
                 *         &lt;/choice>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "pointType",
                    "latlon"
                })
                public static class Point {

                    @XmlElement(required = true)
                    protected String pointType;
                    protected CrawlerConfig.LuceneField.Property.Xpath.Point.Latlon latlon;

                    /**
                     * Gets the value of the pointType property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getPointType() {
                        return pointType;
                    }

                    /**
                     * Sets the value of the pointType property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setPointType(String value) {
                        this.pointType = value;
                    }

                    /**
                     * Gets the value of the latlon property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link CrawlerConfig.LuceneField.Property.Xpath.Point.Latlon }
                     *     
                     */
                    public CrawlerConfig.LuceneField.Property.Xpath.Point.Latlon getLatlon() {
                        return latlon;
                    }

                    /**
                     * Sets the value of the latlon property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link CrawlerConfig.LuceneField.Property.Xpath.Point.Latlon }
                     *     
                     */
                    public void setLatlon(CrawlerConfig.LuceneField.Property.Xpath.Point.Latlon value) {
                        this.latlon = value;
                    }


                    /**
                     * <p>Java class for anonymous complex type.
                     * 
                     * <p>The following schema fragment specifies the expected content contained within this class.
                     * 
                     * <pre>
                     * &lt;complexType>
                     *   &lt;complexContent>
                     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                     *       &lt;sequence>
                     *         &lt;element name="lat" type="{http://www.w3.org/2001/XMLSchema}string"/>
                     *         &lt;element name="long" type="{http://www.w3.org/2001/XMLSchema}string"/>
                     *       &lt;/sequence>
                     *     &lt;/restriction>
                     *   &lt;/complexContent>
                     * &lt;/complexType>
                     * </pre>
                     * 
                     * 
                     */
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = {
                        "lat",
                        "_long"
                    })
                    public static class Latlon {

                        @XmlElement(required = true)
                        protected String lat;
                        @XmlElement(name = "long", required = true)
                        protected String _long;

                        /**
                         * Gets the value of the lat property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getLat() {
                            return lat;
                        }

                        /**
                         * Sets the value of the lat property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setLat(String value) {
                            this.lat = value;
                        }

                        /**
                         * Gets the value of the long property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getLong() {
                            return _long;
                        }

                        /**
                         * Sets the value of the long property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setLong(String value) {
                            this._long = value;
                        }

                    }

                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="exterior" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="interior" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "exterior",
                    "interior"
                })
                public static class Polygon {

                    @XmlElement(required = true)
                    protected String exterior;
                    protected List<String> interior;

                    /**
                     * Gets the value of the exterior property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getExterior() {
                        return exterior;
                    }

                    /**
                     * Sets the value of the exterior property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setExterior(String value) {
                        this.exterior = value;
                    }

                    /**
                     * Gets the value of the interior property.
                     * 
                     * <p>
                     * This accessor method returns a reference to the live list,
                     * not a snapshot. Therefore any modification you make to the
                     * returned list will be present inside the JAXB object.
                     * This is why there is not a <CODE>set</CODE> method for the interior property.
                     * 
                     * <p>
                     * For example, to add a new item, do as follows:
                     * <pre>
                     *    getInterior().add(newItem);
                     * </pre>
                     * 
                     * 
                     * <p>
                     * Objects of the following type(s) are allowed in the list
                     * {@link String }
                     * 
                     * 
                     */
                    public List<String> getInterior() {
                        if (interior == null) {
                            interior = new ArrayList<String>();
                        }
                        return this.interior;
                    }

                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="namespace" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "namespace"
    })
    public static class NamespaceList {

        @XmlElement(required = true)
        protected List<String> namespace;

        /**
         * Gets the value of the namespace property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the namespace property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getNamespace().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getNamespace() {
            if (namespace == null) {
                namespace = new ArrayList<String>();
            }
            return this.namespace;
        }

    }

}
