//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.31 at 04:35:10 午後 JST 
//


package org.dbgrid.csw.schema.crawler;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.dbgrid.schema.crawler package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.dbgrid.schema.crawler
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CrawlerConfig.LuceneField.Property.Xpath.Bbox.Envelope }
     * 
     */
    public CrawlerConfig.LuceneField.Property.Xpath.Bbox.Envelope createCrawlerConfigLuceneFieldPropertyXpathBboxEnvelope() {
        return new CrawlerConfig.LuceneField.Property.Xpath.Bbox.Envelope();
    }

    /**
     * Create an instance of {@link CrawlerConfig.LuceneField }
     * 
     */
    public CrawlerConfig.LuceneField createCrawlerConfigLuceneField() {
        return new CrawlerConfig.LuceneField();
    }

    /**
     * Create an instance of {@link CrawlerConfig.NamespaceList }
     * 
     */
    public CrawlerConfig.NamespaceList createCrawlerConfigNamespaceList() {
        return new CrawlerConfig.NamespaceList();
    }

    /**
     * Create an instance of {@link CrawlerConfig.LuceneField.Property.Xpath.Bbox.NWES }
     * 
     */
    public CrawlerConfig.LuceneField.Property.Xpath.Bbox.NWES createCrawlerConfigLuceneFieldPropertyXpathBboxNWES() {
        return new CrawlerConfig.LuceneField.Property.Xpath.Bbox.NWES();
    }

    /**
     * Create an instance of {@link CrawlerConfig.LuceneField.Property.Xpath.Polygon }
     * 
     */
    public CrawlerConfig.LuceneField.Property.Xpath.Polygon createCrawlerConfigLuceneFieldPropertyXpathPolygon() {
        return new CrawlerConfig.LuceneField.Property.Xpath.Polygon();
    }

    /**
     * Create an instance of {@link CrawlerConfig.LuceneField.Property.Xpath.Point.Latlon }
     * 
     */
    public CrawlerConfig.LuceneField.Property.Xpath.Point.Latlon createCrawlerConfigLuceneFieldPropertyXpathPointLatlon() {
        return new CrawlerConfig.LuceneField.Property.Xpath.Point.Latlon();
    }

    /**
     * Create an instance of {@link CrawlerConfig.LuceneField.Property.Xpath.Point }
     * 
     */
    public CrawlerConfig.LuceneField.Property.Xpath.Point createCrawlerConfigLuceneFieldPropertyXpathPoint() {
        return new CrawlerConfig.LuceneField.Property.Xpath.Point();
    }

    /**
     * Create an instance of {@link CrawlerConfig.LuceneField.Property.Xpath }
     * 
     */
    public CrawlerConfig.LuceneField.Property.Xpath createCrawlerConfigLuceneFieldPropertyXpath() {
        return new CrawlerConfig.LuceneField.Property.Xpath();
    }

    /**
     * Create an instance of {@link CrawlerConfig.LuceneField.Property.Xpath.Bbox }
     * 
     */
    public CrawlerConfig.LuceneField.Property.Xpath.Bbox createCrawlerConfigLuceneFieldPropertyXpathBbox() {
        return new CrawlerConfig.LuceneField.Property.Xpath.Bbox();
    }

    /**
     * Create an instance of {@link CrawlerConfig.LuceneField.Property }
     * 
     */
    public CrawlerConfig.LuceneField.Property createCrawlerConfigLuceneFieldProperty() {
        return new CrawlerConfig.LuceneField.Property();
    }

    /**
     * Create an instance of {@link CrawlerConfig }
     * 
     */
    public CrawlerConfig createCrawlerConfig() {
        return new CrawlerConfig();
    }

}
